---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker Image
      command: docker pull your-dockerhub-username/flask-weather-app

    - name: Run Docker Container
      command: docker run -d -p 5000:5000 your-dockerhub-username/flask-weather-app

