---
- hosts: all
  become: true
  tasks:
    - name: Install required packages
      yum:
        name: yum-utils
        state: present

    - name: Remove conflicting podman-docker package
      yum:
        name: podman-docker
        state: absent

    - name: Add Docker CE repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image
      command: docker pull wahdann/flask-weather-app

    - name: Run Docker Container
      command: docker run -d -p 5000:5000 wahdann/flask-weather-app
